name: Deploy

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan 51.178.28.206 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - run: ssh debian@51.178.28.206 "ls"